### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ramesh-emandi** [JeroenMols/LandscapeVideoCamera#11]
It works very well on landscape mode.
I am interested to know the reason why you preferred only Landscape orientation?

**Comment by JeroenMols** [comment]
Because almost all monitors/TV's have a landscape orientation. Portrait video's don't really make an efficient use of that screen real estate and are usually less pleasant to watch.

I actually created this library for my [wedding app](https://play.google.com/store/apps/details?id=com.jmolsmobile.brittenjeroen) where guests could post video's/images on a micro social network. For that I preferred all video's to be landscape. :)

But if you want you can simply create your own Activity, reuse all recording logic and build an app that records both landscape and portrait.

**Comment by ramesh-emandi** [comment]
Makes sense. Nice app.
