### ISSUE TITLE
Don't stop when screen off

### ISSUE THREAD

**Issue by john-peterson** [JeroenMols/LandscapeVideoCamera#6]
this app https://play.google.com/store/apps/details?id=rubberbigpepper.lgCamera let me save battery by turning off the screen while recoding. this app stop recording on screen off. why? i set a limit. why would turning off the screen mean i wanna stop recording?

**Comment by JeroenMols** [comment]
Hi @john-peterson,

That is because a camera resource is an expensive resource to use and keeping it in use will block other apps from using it. Just disabling the screen however could work.

I suggest you create your own custom VideoCaptureActivity and directly talk to the VideoRecorder. This feature should be really really easy to add.

Jeroen
